services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
  
  app:
    build: .
    container_name: python_app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/keyvalue_db
